- name: download jboss taz file
  get_url:
    url: https://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.tar.gz
    dest: /mnt/jboss
    



- name: extract jboss tar file
  unarchive: 
    src: /mnt/jboss/jboss-as-7.1.1.Final.zip
    dest: /mnt/jboss/
    remote_src: yes