---
# file: webservers.yml
- hosts: all
  become: true
  become_method: sudo
  become_user: ansible



  roles:
     - dir
  #  - user
  #  - yum  
  #  - docker
  #  - java
  #  - jenkins
  #  - maven
  #  - tasks
  #  - tomcat
  #  - jenkins
  #  - nginx
     - splunk
  #  - jboss