---
# file: webservers.yml
- hosts: all
  become: true
  become_method: su
  become_user: ansible
  become_user: root


  roles:
#    - dir
#    - docker
#    - java
#    - maven
#    - tasks
     - tomcat