 ---
#   file: ansible
 - hosts: all
   remote_user: root
   become: yes
   become_method: su
   become_user: root
 
  roles:
    - dir
    # - webtier

  # roles:
  #   - dir
  # #  - tomcat
  #  - java
  #  - docker
  #  - maven
#    - webtier