# - name: download splunk
#   get_url:
#     url: https://download.splunk.com/products/splunk/releases/7.3.0/linux/splunk-7.3.0-657388c7a488-Linux-x86_64.tgz
#     dest: /mnt/splunk


# - name: download and extract splunk trz
#   unarchive:
#     src: /mnt/splunk/splunk-7.3.0-657388c7a488-Linux-x86_64.tgz
#     dest: /mnt/splunk
#     remote_src: yes


# - name: splunk-7.3.0-657388c7a488-Linux-x86_64.tgz delete file example
#   file:
#     path: /mnt/splunk/apache-tomcat-9.0.20.tar.gz
#     state: absent



- name: accept-license
  tags:
    - install
  shell: /mnt/splunk/splunk/bin/splunk start --accept-license  

- name: Enable init script
  tags:
    - install
  shell: /mnt/splunk/splunk/bin/splunk enable boot-start  