# - name: download jenkins
#   get_url: 
#     url: http://updates.jenkins-ci.org/download/war/2.7.3/jenkins.war
#     dest: /opt/jenkins/
    


# - name: extract jenkin tar file
#   unarchive: 
#     src: /opt/jenkins/apache-maven-3.5.4-bin.tar.gz
#     dest: /opt/jenkins/
#     remote_src: yes


    - name: Download jenkins.repo
      get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins Key
      rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start & Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true