- name: download tomcat
  get_url:
    url: http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.51/bin/apache-tomcat-8.5.51.tar.gz
    dest: /opt/tomcat
#    mode: 0775

- name: download and extract trex
  unarchive:
    src: /opt/tomcat/apache-tomcat-8.5.51.tar.gz
    dest: /opt/tomcat
    remote_src: yes



- name: apache-tomcat-8.5.46.tar.gz delete file example
  file:
    path: /opt/tomcat/apache-tomcat-8.5.51.tar.gz
    state: absent

# - name: execute start.sh file
#   command: sh /opt/tomcat/apache-tomcat-8.5.51.tar.gz/bin/startup.sh


- name: execute start.sh file
  tags:
    - install
  shell: sh /opt/tomcat/apache-tomcat-8.5.51/bin/startup.sh