- name: download tomcat
  get_url:
    url: http://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.20/bin/apache-tomcat-9.0.20.tar.gz
    dest: /u01/tomcat
    mode: 0775


- name: archive tomcat file
  shell: tar -zczf /u01/tomcat/apache-tomcat-9.0.20.tar.gz