- name: install tomcat
  get_url:
    url: http://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.20/bin/apache-tomcat-9.0.20.tar.gz
    dest: /opt/tomcat
    mode: 0775
    checksum: sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c


- name: extract tomcat file
  unarchive:
    scr: apache-tomcat-8.5.37.tar.gz
    dest: /opt/tomcat