- name: install tomcat
  get_url:
    url: https://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.37/bin/apache-tomcat-8.5.37.tar.gz
    dest: /opt/tomcat


- name: extract tomcat file
  unarchive:
    scr: apache-tomcat-8.5.37.tar.gz
    dest: /opt/tomcat