- name: download tomcat
  get_url:
    url: http://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.20/bin/apache-tomcat-9.0.20.tar.gz
    dest: /opt/tomcat
    mode: 0775

- name: download and extract trex
  unarchive:
    src: /opt/tomcat/apache-tomcat-9.0.20.tar.gz
    dest: /opt/tomcat
    remote_src: yes



- name: apache-tomcat-9.0.20.tar.gz delete file example
  file:
    path: /opt/tomcat/apache-tomcat-9.0.20.tar.gz
    state: absent
    
    




- name: execute start.sh file
  command: sh /opt/tomcat/apache-tomcat-9.0.20/bin/startup.sh