 - name: Creates directory
   file:
     path: /home/ansible/docker
     state: directory


 - name: install docker
   yum:
    name: docker
    state: absent

#  - name: install docker using pip
#    pip:
#     name: docker
#     state: latest

# # handlers file for docker-example
#  - name: restart-docker-service
#    service:
#     name: docker
#     state: restarted
 
# # pulling docker image
#  - name:  pull docker images from docker hub
#    docker_image: 
#     name: centos-7
#     source: pull

# # Installing docker-compose
#  - name: install latest version of Docker-compose
#    yum:
#     name: docker-compose
#     state: latest
